language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
  licenses:
    - '.+'