language: android
android:
  components:

    - build-tools-23.0.3

    - android-23

#    - extra-android-support
#    - extra-google-m2repository
#    - sys-img-armeabi-v7a-android-23
#    - extra-android-m2repository
