language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_TARGET=android-25
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

notifications:
  slack:
    rooms:
      - androidgigigo:iqpT5BG5SCI5HgECBCdqK0zt#integrations
    on_success: always
    on_failure: always

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-22.0.1
    - build-tools-26.0.2
    - build-tools-26.1.0
    - android-22
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-26
    - extra-google-google_play_services
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - cd $TRAVIS_BUILD_DIR/
  - pip install --user codecov

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew :showcase:build
  - ./gradlew :showcase:check