language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-25
  - ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository
