sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - tools
  - android-24
  - build-tools-24.0.3
  - platform-tools
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- echo "sdk.dir=$ANDROID_HOME" > local.properties
#notifications:
#  webhooks:
#    urls:
#    - secure: A1YKQ32CBvm6s0gfwb+UKZuniYdb5ZUENvSpSt/k7nQmyZ9U0p4Sn8qqSSKfRyYVRLT3C3za53aoqFwSqFj6mZ82YO6HbKl/RqhGQLmdIPpyhXKUE5xKlyMbgmAYRBDh41+eQ1i22mkT+jiqVW06VFSB0YyeDKAZjXxk8hfyIUA=
#    on_success: change
#    on_failure: always